# Generated by Django 4.2.3 on 2023-10-13 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_task_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('Low', 'low'), ('Medium', 'Medium'), ('High', 'High')], default='L', max_length=10),
        ),
    ]
